/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutThePractitionerRouteImport } from './routes/about-the-practitioner'
import { Route as BenefitsOfMassageRouteImport } from './routes/benefits-of-massage'
import { Route as ExclusiveServicesRouteImport } from './routes/exclusive-services'
import { Route as FeaturedTherapiesRatesRouteImport } from './routes/featured-therapies-rates'
import { Route as FrequentlyAskedQuestionsRouteImport } from './routes/frequently-asked-questions'
import { Route as TestimonialsRouteImport } from './routes/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutThePractitionerRoute = AboutThePractitionerRouteImport.update({
  id: '/about-the-practitioner',
  path: '/about-the-practitioner',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsOfMassageRoute = BenefitsOfMassageRouteImport.update({
  id: '/benefits-of-massage',
  path: '/benefits-of-massage',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusiveServicesRoute = ExclusiveServicesRouteImport.update({
  id: '/exclusive-services',
  path: '/exclusive-services',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedTherapiesRatesRoute = FeaturedTherapiesRatesRouteImport.update({
  id: '/featured-therapies-rates',
  path: '/featured-therapies-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const FrequentlyAskedQuestionsRoute =
  FrequentlyAskedQuestionsRouteImport.update({
    id: '/frequently-asked-questions',
    path: '/frequently-asked-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-the-practitioner': typeof AboutThePractitionerRoute
  '/benefits-of-massage': typeof BenefitsOfMassageRoute
  '/exclusive-services': typeof ExclusiveServicesRoute
  '/featured-therapies-rates': typeof FeaturedTherapiesRatesRoute
  '/frequently-asked-questions': typeof FrequentlyAskedQuestionsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-the-practitioner': typeof AboutThePractitionerRoute
  '/benefits-of-massage': typeof BenefitsOfMassageRoute
  '/exclusive-services': typeof ExclusiveServicesRoute
  '/featured-therapies-rates': typeof FeaturedTherapiesRatesRoute
  '/frequently-asked-questions': typeof FrequentlyAskedQuestionsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-the-practitioner': typeof AboutThePractitionerRoute
  '/benefits-of-massage': typeof BenefitsOfMassageRoute
  '/exclusive-services': typeof ExclusiveServicesRoute
  '/featured-therapies-rates': typeof FeaturedTherapiesRatesRoute
  '/frequently-asked-questions': typeof FrequentlyAskedQuestionsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-the-practitioner'
    | '/benefits-of-massage'
    | '/exclusive-services'
    | '/featured-therapies-rates'
    | '/frequently-asked-questions'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-the-practitioner'
    | '/benefits-of-massage'
    | '/exclusive-services'
    | '/featured-therapies-rates'
    | '/frequently-asked-questions'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about-the-practitioner'
    | '/benefits-of-massage'
    | '/exclusive-services'
    | '/featured-therapies-rates'
    | '/frequently-asked-questions'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutThePractitionerRoute: typeof AboutThePractitionerRoute
  BenefitsOfMassageRoute: typeof BenefitsOfMassageRoute
  ExclusiveServicesRoute: typeof ExclusiveServicesRoute
  FeaturedTherapiesRatesRoute: typeof FeaturedTherapiesRatesRoute
  FrequentlyAskedQuestionsRoute: typeof FrequentlyAskedQuestionsRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-the-practitioner': {
      id: '/about-the-practitioner'
      path: '/about-the-practitioner'
      fullPath: '/about-the-practitioner'
      preLoaderRoute: typeof AboutThePractitionerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits-of-massage': {
      id: '/benefits-of-massage'
      path: '/benefits-of-massage'
      fullPath: '/benefits-of-massage'
      preLoaderRoute: typeof BenefitsOfMassageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusive-services': {
      id: '/exclusive-services'
      path: '/exclusive-services'
      fullPath: '/exclusive-services'
      preLoaderRoute: typeof ExclusiveServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured-therapies-rates': {
      id: '/featured-therapies-rates'
      path: '/featured-therapies-rates'
      fullPath: '/featured-therapies-rates'
      preLoaderRoute: typeof FeaturedTherapiesRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frequently-asked-questions': {
      id: '/frequently-asked-questions'
      path: '/frequently-asked-questions'
      fullPath: '/frequently-asked-questions'
      preLoaderRoute: typeof FrequentlyAskedQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutThePractitionerRoute: AboutThePractitionerRoute,
  BenefitsOfMassageRoute: BenefitsOfMassageRoute,
  ExclusiveServicesRoute: ExclusiveServicesRoute,
  FeaturedTherapiesRatesRoute: FeaturedTherapiesRatesRoute,
  FrequentlyAskedQuestionsRoute: FrequentlyAskedQuestionsRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
